In [2]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_sales_dataset_15000_rows (2).csv (1).xlsx to ecommerce_sales_dataset_15000_rows (2).csv (1).xlsx

In [50]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_excel("ecommerce_sales_dataset_15000_rows (2).csv (1).xlsx")
df

,Order_ID,Order_Date,Customer_ID,Product_Category,Product_Name,State,City,Payment_Mode,Quantity,Sales_Amount,Discount,Profit
0,ORD100000,2023-07-11,CUST8187,Home & Kitchen,Air Fryer,Uttar Pradesh,Chennai,Cash on Delivery,5,1225,0.11,213.18
1,ORD100001,2023-06-28,CUST8470,Electronics,Laptop,Rajasthan,Ahmedabad,Credit Card,3,2355,0.21,312.75
2,ORD100002,2024-01-08,CUST3542,Electronics,Camera,Uttar Pradesh,Jaipur,Debit Card,4,1948,0.29,118.10
3,ORD100003,2023-06-28,CUST8975,Electronics,Camera,Rajasthan,Bangalore,Credit Card,1,1438,0.17,284.36
4,ORD100004,2024-03-05,CUST3112,Beauty,Hair Dryer,Rajasthan,Chennai,Net Banking,1,727,0.07,124.67
...,...,...,...,...,...,...,...,...,...,...,...,...
14995,ORD114995,2024-05-29,CUST8386,Beauty,Makeup Kit,Delhi,Bangalore,Cash on Delivery,2,1904,0.00,216.07
14996,ORD114996,2024-01-05,CUST3889,Electronics,Laptop,Karnataka,Bangalore,Net Banking,1,529,0.03,73.95
14997,ORD114997,2024-08-22,CUST7181,Home & Kitchen,Cookware Set,Uttar Pradesh,Lucknow,Net Banking,4,3124,0.21,238.31
14998,ORD114998,2024-09-20,CUST6964,Electronics,Tablet,Karnataka,Mumbai,Net Banking,3,5106,0.07,445.94
14999,ORD114999,2023-02-28,CUST9337,Beauty,Face Wash,Rajasthan,Bangalore,Debit Card,2,3176,0.26,325.56

In [34]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Product_Category    0
Product_Name        0
State               0
City                0
Payment_Mode        0
Quantity            0
Sales_Amount        0
Discount            0
Profit              0
dtype: int64

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          15000 non-null  object
 1   Order_Date        15000 non-null  datetime64[ns]
 2   Customer_ID       15000 non-null  object
 3   Product_Category  15000 non-null  object
 4   Product_Name      15000 non-null  object
 5   State             15000 non-null  object
 6   City              15000 non-null  object
 7   Payment_Mode      15000 non-null  object
 8   Quantity          15000 non-null  int64
 9   Sales_Amount      15000 non-null  int64
 10  Discount          15000 non-null  float64
 11  Profit            15000 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 1.4+ MB

In [36]:
df.describe()

,Order_Date,Quantity,Sales_Amount,Discount,Profit
count,15000,15000.000000,15000.000000,15000.000000,15000.000000
mean,2024-01-01 04:03:38.880000,3.012733,3292.322667,0.150105,491.851406
min,2023-01-01 00:00:00,1.000000,200.000000,0.000000,12.320000
25%,2023-07-06 00:00:00,2.000000,1422.750000,0.070000,183.435000
50%,2024-01-02 00:00:00,3.000000,2736.000000,0.150000,365.285000
75%,2024-07-01 00:00:00,4.000000,4776.000000,0.220000,680.962500
max,2024-12-31 00:00:00,5.000000,10000.000000,0.300000,2484.640000
std,NaN,1.412529,2312.812147,0.086968,413.845825

In [37]:
df.shape

(15000, 12)

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

In [40]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category',
       'product_name', 'state', 'city', 'payment_mode', 'quantity',
       'sales_amount', 'discount', 'profit'],
      dtype='object')

In [41]:
df.head()

,order_id,order_date,customer_id,product_category,product_name,state,city,payment_mode,quantity,sales_amount,discount,profit
0,ORD100000,2023-07-11,CUST8187,Home & Kitchen,Air Fryer,Uttar Pradesh,Chennai,Cash on Delivery,5,1225,0.11,213.18
1,ORD100001,2023-06-28,CUST8470,Electronics,Laptop,Rajasthan,Ahmedabad,Credit Card,3,2355,0.21,312.75
2,ORD100002,2024-01-08,CUST3542,Electronics,Camera,Uttar Pradesh,Jaipur,Debit Card,4,1948,0.29,118.10
3,ORD100003,2023-06-28,CUST8975,Electronics,Camera,Rajasthan,Bangalore,Credit Card,1,1438,0.17,284.36
4,ORD100004,2024-03-05,CUST3112,Beauty,Hair Dryer,Rajasthan,Chennai,Net Banking,1,727,0.07,124.67

In [48]:
df.dtypes

order_id                    object
order_date          datetime64[ns]
customer_id                 object
product_category            object
product_name                object
state                       object
city                        object
payment_mode                object
quantity                     int64
sales_amount                 int64
discount                   float64
profit                     float64
dtype: object

In [42]:
col = ["quantity","sales_amount","discount","profit"]
for c in col:
  df[c] = pd.to_numeric(df[c],errors='coerce')

In [43]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
product_name        0
state               0
city                0
payment_mode        0
quantity            0
sales_amount        0
discount            0
profit              0
dtype: int64

In [44]:
df.head()

,order_id,order_date,customer_id,product_category,product_name,state,city,payment_mode,quantity,sales_amount,discount,profit
0,ORD100000,2023-07-11,CUST8187,Home & Kitchen,Air Fryer,Uttar Pradesh,Chennai,Cash on Delivery,5,1225,0.11,213.18
1,ORD100001,2023-06-28,CUST8470,Electronics,Laptop,Rajasthan,Ahmedabad,Credit Card,3,2355,0.21,312.75
2,ORD100002,2024-01-08,CUST3542,Electronics,Camera,Uttar Pradesh,Jaipur,Debit Card,4,1948,0.29,118.10
3,ORD100003,2023-06-28,CUST8975,Electronics,Camera,Rajasthan,Bangalore,Credit Card,1,1438,0.17,284.36
4,ORD100004,2024-03-05,CUST3112,Beauty,Hair Dryer,Rajasthan,Chennai,Net Banking,1,727,0.07,124.67

In [52]:
df.to_excel("cleaned_ecommerce_sales_dataset_15000_rows.xlsx",index = False)
print("Data cleaning completed!")

Data cleaning completed!

In [53]:
from google.colab import files
files.download("cleaned_ecommerce_sales_dataset_15000_rows.xlsx")

In [54]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
product_name        0
state               0
city                0
payment_mode        0
quantity            0
sales_amount        0
discount            0
profit              0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(0)