In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 📊 Project Retail Sales & Profit Analysis.xlsx to 📊 Project Retail Sales & Profit Analysis.xlsx

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("📊 Project Retail Sales & Profit Analysis.xlsx")
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,2012-01-10 00:00:00,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-02-10 00:00:00
2,50,293,2012-01-10 00:00:00,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-03-10 00:00:00
3,80,483,2011-10-07 00:00:00,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-12-07 00:00:00
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                8399 non-null   int64
 1   Order ID              8399 non-null   int64
 2   Order Date            8399 non-null   object
 3   Order Priority        8399 non-null   object
 4   Order Quantity        8399 non-null   int64
 5   Sales                 8399 non-null   float64
 6   Discount              8399 non-null   float64
 7   Ship Mode             8399 non-null   object
 8   Profit                8399 non-null   float64
 9   Unit Price            8399 non-null   float64
 10  Shipping Cost         8399 non-null   float64
 11  Customer Name         8399 non-null   object
 12  Province              8399 non-null   object
 13  Region                8399 non-null   object
 14  Customer Segment      8399 non-null   object
 15  Product Category      8399 non-null   object
 16  Product Sub-Category  8399 non-null   object
 17  Product Name          8399 non-null   object
 18  Product Container     8399 non-null   object
 19  Product Base Margin   8336 non-null   float64
 20  Ship Date             8399 non-null   object
dtypes: float64(6), int64(3), object(12)
memory usage: 1.3+ MB

In [ ]:
df.describe()

,Row ID,Order ID,Order Quantity,Sales,Discount,Profit,Unit Price,Shipping Cost,Product Base Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,4200.000000,29965.179783,25.571735,1775.878179,0.049671,181.184424,89.346259,12.838557,0.512513
std,2424.726789,17260.883447,14.481071,3585.050525,0.031823,1196.653371,290.354383,17.264052,0.135589
min,1.000000,3.000000,1.000000,2.240000,0.000000,-14140.700000,0.990000,0.490000,0.350000
25%,2100.500000,15011.500000,13.000000,143.195000,0.020000,-83.315000,6.480000,3.300000,0.380000
50%,4200.000000,29857.000000,26.000000,449.420000,0.050000,-1.500000,20.990000,6.070000,0.520000
75%,6299.500000,44596.000000,38.000000,1709.320000,0.080000,162.750000,85.990000,13.990000,0.590000
max,8399.000000,59973.000000,50.000000,89061.050000,0.250000,27220.690000,6783.020000,164.730000,0.850000

In [ ]:
df.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

In [ ]:
df['Order ID'].duplicated().sum()

np.int64(2903)

In [ ]:
df.shape

(8399, 21)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.head()

,row_id,order_id,order_date,order_priority,order_quantity,sales,discount,ship_mode,profit,unit_price,...,customer_name,province,region,customer_segment,product_category,product_sub-category,product_name,product_container,product_base_margin,ship_date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,2012-01-10 00:00:00,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-02-10 00:00:00
2,50,293,2012-01-10 00:00:00,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-03-10 00:00:00
3,80,483,2011-10-07 00:00:00,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-12-07 00:00:00
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [ ]:
df.rename(
    columns={'product_sub-category':'product_sub_category'},
    inplace=True
)

In [ ]:
df["product_base_margin"] = df["product_base_margin"].fillna(
    df["product_base_margin"].median()
)
df.head()

,row_id,order_id,order_date,order_priority,order_quantity,sales,discount,ship_mode,profit,unit_price,...,customer_name,province,region,customer_segment,product_category,product_sub_category,product_name,product_container,product_base_margin,ship_date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,2012-01-10 00:00:00,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-02-10 00:00:00
2,50,293,2012-01-10 00:00:00,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-03-10 00:00:00
3,80,483,2011-10-07 00:00:00,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-12-07 00:00:00
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [ ]:
numeric_cols = [
    "order_quantity",
    "sales",
    "profit",
    "discount",
    "unit_price",
    "shipping_cost",
    "product_base_margin"
]
df[numeric_cols].head()

,order_quantity,sales,profit,discount,unit_price,shipping_cost,product_base_margin
0,6,261.5400,-213.25,0.04,38.94,35.00,0.80
1,49,10123.0200,457.81,0.07,208.16,68.02,0.58
2,27,244.5700,46.71,0.01,8.69,2.99,0.39
3,30,4965.7595,1198.97,0.08,195.99,3.99,0.58
4,19,394.2700,30.94,0.08,21.78,5.94,0.50

In [ ]:
df['discount'] = df['discount']*100
df['product_base_margin'] = df['product_base_margin']*100
df[numeric_cols].head()

,order_quantity,sales,profit,discount,unit_price,shipping_cost,product_base_margin
0,6,261.5400,-213.25,4.0,38.94,35.00,80.0
1,49,10123.0200,457.81,7.0,208.16,68.02,58.0
2,27,244.5700,46.71,1.0,8.69,2.99,39.0
3,30,4965.7595,1198.97,8.0,195.99,3.99,58.0
4,19,394.2700,30.94,8.0,21.78,5.94,50.0

In [ ]:
df['sales'] = df['sales'].astype(int)
df['profit'] = df['profit'].astype(int)
df['discount'] = df['discount'].astype(int)
df['unit_price'] = df['unit_price'].astype(int)
df['shipping_cost'] = df['shipping_cost'].astype(int)
df['product_base_margin'] = df['product_base_margin'].astype(int)
df.head()

,row_id,order_id,order_date,order_priority,order_quantity,sales,discount,ship_mode,profit,unit_price,...,customer_name,province,region,customer_segment,product_category,product_sub_category,product_name,product_container,product_base_margin,ship_date
0,1,3,10/13/2010,Low,6,261,4,Regular Air,-213,38,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,80,10/20/2010
1,49,293,2012-01-10 00:00:00,High,49,10123,7,Delivery Truck,457,208,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,57,2012-02-10 00:00:00
2,50,293,2012-01-10 00:00:00,High,27,244,1,Regular Air,46,8,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,39,2012-03-10 00:00:00
3,80,483,2011-10-07 00:00:00,High,30,4965,8,Regular Air,1198,195,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,57,2011-12-07 00:00:00
4,85,515,8/28/2010,Not Specified,19,394,8,Regular Air,30,21,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,50,8/30/2010

In [ ]:
df['order_date'].unique()

array(['10/13/2010', datetime.datetime(2012, 1, 10, 0, 0),
       datetime.datetime(2011, 10, 7, 0, 0), ..., '11/13/2009',
       '1/14/2012', datetime.datetime(2009, 9, 2, 0, 0)], dtype=object)

In [ ]:
df['order_date'].astype(str)

0                10/13/2010
1       2012-01-10 00:00:00
2       2012-01-10 00:00:00
3       2011-10-07 00:00:00
4                 8/28/2010
               ...
8394    2010-09-08 00:00:00
8395    2010-09-08 00:00:00
8396    2011-08-04 00:00:00
8397    2011-08-04 00:00:00
8398    2009-08-02 00:00:00
Name: order_date, Length: 8399, dtype: object

In [ ]:
def fix_date(date_str):
    date_str = str(date_str).replace("/", "-")

    parts = date_str.split("-")
    if len(parts) != 3:
        return date_str

    p1, p2, p3 = parts

    try:
        p1 = int(p1)
        p2 = int(p2)
    except:
        return date_str

    # If first part is month and second part is day
    if p1 <= 12 and p2 > 12:
        return f"{p2:02d}-{p1:02d}-{p3}"

    # Otherwise leave unchanged
    return date_str

df['order_date'] = df['order_date'].apply(fix_date)
df['ship_date'] = df['ship_date'].apply(fix_date)

In [ ]:
df['order_date'].head(10)
print(df['ship_date'].head(10))

0             20-10-2010
1    2012-02-10 00:00:00
2    2012-03-10 00:00:00
3    2011-12-07 00:00:00
4             30-08-2010
5             30-08-2010
6             17-06-2011
7             18-06-2011
8             25-03-2011
9             26-02-2010
Name: ship_date, dtype: object

In [ ]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

df['ship_date'] = pd.to_datetime(
    df['ship_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [ ]:
df['order_date'].head(10)

0   2010-10-13
1   2012-01-10
2   2012-01-10
3   2011-10-07
4   2010-08-28
5   2010-08-28
6   2011-06-17
7   2011-06-17
8   2011-03-24
9   2010-02-26
Name: order_date, dtype: datetime64[ns]

In [ ]:
# df['order_date'] = df['order_date'].dt.strftime('%d-%m-%Y')
# df['ship_date'] = df['ship_date'].dt.strftime('%d-%m-%Y')

In [ ]:
# df['order_date'] = pd.to_datetime(
#     df['order_date'],
#     format='%d-%m-%Y'
# )

# df['ship_date'] = pd.to_datetime(
#     df['ship_date'],
#     format='%d-%m-%Y'
# )

In [ ]:
df[['order_date', 'ship_date']].dtypes

order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object

In [ ]:
df['order_date'].head(100)

0    2010-10-13
1    2012-01-10
2    2012-01-10
3    2011-10-07
4    2010-08-28
        ...
95   2011-05-27
96   2011-05-27
97   2010-08-23
98   2011-08-19
99   2012-03-01
Name: order_date, Length: 100, dtype: datetime64[ns]

In [ ]:
df['order_date'].isnull().sum()

np.int64(0)

In [ ]:
df['ship_date'].head(15)

0    2010-10-20
1    2012-02-10
2    2012-03-10
3    2011-12-07
4    2010-08-30
5    2010-08-30
6    2011-06-17
7    2011-06-18
8    2011-03-25
9    2010-02-26
10   2010-11-24
11   2010-11-24
12   2012-09-06
13   2012-10-06
14   2012-04-08
Name: ship_date, dtype: datetime64[ns]

In [ ]:
df['ship_date'].isnull().sum()

np.int64(0)

In [ ]:
print(df.loc[df['order_date'].isna(), 'order_date'])

Series([], Name: order_date, dtype: datetime64[ns])

In [ ]:
df.dtypes

row_id                           int64
order_id                         int64
order_date              datetime64[ns]
order_priority                  object
order_quantity                   int64
sales                            int64
discount                         int64
ship_mode                       object
profit                           int64
unit_price                       int64
shipping_cost                    int64
customer_name                   object
province                        object
region                          object
customer_segment                object
product_category                object
product_sub_category            object
product_name                    object
product_container               object
product_base_margin              int64
ship_date               datetime64[ns]
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

row_id                  0
order_id                0
order_date              0
order_priority          0
order_quantity          0
sales                   0
discount                0
ship_mode               0
profit                  0
unit_price              0
shipping_cost           0
customer_name           0
province                0
region                  0
customer_segment        0
product_category        0
product_sub_category    0
product_name            0
product_container       0
product_base_margin     0
ship_date               0
dtype: int64

In [ ]:
df.to_excel("cleaned_retail_sales.xlsx", index=False)
print("Data cleaning completed!")

Data cleaning completed!

In [ ]:
from google.colab import files
files.download("cleaned_retail_sales.xlsx")